### ISSUE TITLE
Incompatible with Arduino IDE v1.6.7

### ISSUE THREAD

**Issue by imranmunshi** [brumster/EDTracker2_ArduinoHardware#1]
Gives error:
Property line '﻿##############################################################' in file /usr/share/arduino/hardware/edtracker/avr/boards.txt is invalid

Tried editing that but other errors popup.

**Comment by brumster** [comment]
File encoding is incorrect; will fix... leave it with me ;)

**Comment by imranmunshi** [comment]
How can I fix it locally?
I'm on Linux, shall I encode/recode it to a different file encoding? I checked the boards.txt now to be utf-8 encoded.

**Comment by imranmunshi** [comment]
I have made some changes locally which made it compatible with current version, only complains it makes:
<code>Board edtracker:avr:﻿edtracker9250 doesn't define a 'build.board' preference. Auto-set to: AVR_﻿EDTRACKER9250
WARNING: Category '' in library SPI is not valid. Setting to 'Uncategorized'</code>

**Comment by imranmunshi** [comment]
After the edits I did, it seems to work fine with IDE v1.6.7, but it needs to be tested with older versions (if that's required).

**Comment by brumster** [comment]
Indeed, IDE 1.6.7 doesn't seem to like it. I encoded to ASCII and it seems fine along with older IDEs.
There's some code updates I need to do to the main sketches, just formatting stuff, but if it's OK with you I'd like to close this issue related to the Hardware repo....?

**Comment by imranmunshi** [comment]
I have done the required edits locally to get it to work properly with v1.6.7. You may want to take a look at the boards.txt and platform.txt I modified.

**Comment by brumster** [comment]
No problems, please supply link, but platform.txt should not require any updating...

**Comment by imranmunshi** [comment]
File Links:
https://github.com/TAALS/Arduino-MPU-Edtracker/blob/master/edtracker/avr/boards.txt
https://github.com/TAALS/Arduino-MPU-Edtracker/blob/master/edtracker/avr/platform.txt

Raw:
https://github.com/TAALS/Arduino-MPU-Edtracker/raw/master/edtracker/avr/boards.txt
https://github.com/TAALS/Arduino-MPU-Edtracker/raw/master/edtracker/avr/platform.txt

**Comment by imran27** [comment]
I'm sorry, that's my organizational account.

Here's the link: https://github.com/imran27/EDTracker_Hardware_IDEv1.6.7

**Comment by imranmunshi** [comment]
I have supplied the link, you can close the issue if you wish

**Comment by brumster** [comment]
Now compiles under 1.6.7 - closing issue

(As an aside for pre-empting anyone asking why we didn't move to USBPluggable with 1.6.7, we tried, but it compiles way too big on the new libraries, it won't fit on the common Pro Micro hardware)
