### ISSUE TITLE
PI is defined as two different values

### ISSUE THREAD

**Issue by CaseyWagner** [brumster/EDTracker2_ArduinoHardware#2]
This might be intentional, but I'm getting statements in the console giving differing values for PI:

D:\Users\casey\Documents\Arduino\Sketches\EDTracker\EDTracker.ino:78:0: warning: "PI" redefined [enabled by default]

 #define PI    32768.0
 ^
In file included from D:\Users\casey\AppData\Local\Temp\buildd7fb0d4127cf3f363a20538bfdc04135.tmp\sketch\EDTracker.ino.cpp:1:0:

D:\Users\casey\Documents\Arduino\hardware\edtracker\avr\cores\edtracker/Arduino.h:47:0: note: this is the location of the previous definition

 #define PI 3.1415926535897932384626433832795

**Comment by brumster** [comment]
Yes, it's a hang-up from a while back, it is intentional but the variable name was a poor choice. Will consider refactoring to a new variable on the next major update but for now, it's working as expected.

**Comment by brumster** [comment]
Refactored in latest push (DEG90/DEG180 defines)
