### ISSUE TITLE
Can't compile - no INO project available

### ISSUE THREAD

**Issue by padcom** [brumster/EDTracker2_ArduinoHardware#4]
As per the website:

Load the sketch to compile (e.g. File --> Sketchbook --> EDTracker2_9250 --> EDTracker2_9250)

There is no INO file available. What's going on?

**Comment by brumster** [comment]
This isn't the right repo; this is just a collection of Arduino "hardware" files to ease the process of building. You want the other repo :
https://github.com/brumster/EDTracker2
