### ISSUE TITLE
EDTracker software / driver still avalaible? 

### ISSUE THREAD

**Issue by RaffCode-Personal** [brumster/EDTracker2_ArduinoHardware#7]
So, I still have an EDTracker (none wireless, but I think it was the option with the better chip) that I use in my self made pinball controller to simulate the tilt function. 

I just realized that when I upgrade to Windows 11 (or need to reinstall my PC for any reason) that I can't use that anymore because I can't reinstall the software which seems to not be available anymore. 

Do you have by any chance the original driver download?

**Comment by brumster** [comment]
In the other repo ;)

https://github.com/brumster/EDTracker2/tree/master/release/gui
